<?php

namespace Brtriver\SimpleCrudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoRepository extends EntityRepository
{
}
